runtime: php72

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: 1gjc1EjAyJ77ezkd
  CLOUDSQL_DSN: "mysql:dbname=Test;unix_socket=/cloudsql/icomputeproject:us-east1:myinstance"

  
