runtime: php55
api_version: 1
application: iCompute2
version: v1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: index.html

env_variables:
  MYSQL_DSN: icomputeproject:us-east1:myinstance
  MYSQL_USER: root
  MYSQL_PASSWORD: ''

